application/api/controllers/messages.py
import traceback

from datetime import datetime, timezone
from flask import current_app, render_template
from flask_login import current_user
from kombu.exceptions import OperationalError

from application.common import logger
from application.common.constants import MessageCategories
from application.extensions import DATABASE
from application.models.message import Messages
from application.models.user import UserSql
from application.models.setting import SettingsSql
from application.workers.email import send_global_email, send_email


# Determine if the admin has enabled the system for email notifications.
def is_email_enabled() -> bool:
    setting = SettingsSql.query.filter_by(name="APP_ENABLE_EMAIL").first()
    setting_test = setting.value.lower()
    return True if setting_test == "true" else False


def _create_message(
    sender_id: int, recipient_id: int, message: str, subject: str, is_global: bool = False
) -> None:
    # Create message and enter into database.
    new_message = Messages()

    new_message.message = message
    new_message.subject = subject

    new_message.sender_id = sender_id

    # We don't need to set the recipient_id if it's a global message.
    if not is_global:
        new_message.recipient_id = recipient_id

    new_message.is_global = is_global
    new_message.timestamp = datetime.now(timezone.utc)

    try:
        DATABASE.session.add(new_message)
        DATABASE.session.commit()
    except Exception as error:
        message_type = "global" if is_global else "direct"
        logger.critical(f"Unable to create {message_type} message")
        logger.critical(error)
        traceback.print_exc()
        DATABASE.session.rollback()


def _is_user_category_disabled(user_id: int, category: MessageCategories, is_email=False) -> bool:
    is_disabled = False

    user = UserSql.query.filter_by(user_id=user_id).first()
    user_properties = user.properties

    if category == MessageCategories.SOCIAL and not is_email:
        if "NOTIFICATION_DM_SOCIAL_ENABLED" in user_properties:
            is_disabled = True
    elif category == MessageCategories.SOCIAL and is_email:
        if "NOTIFICATION_EMAIL_SOCIAL_ENABLED" in user_properties:
            is_disabled = True
    elif category == MessageCategories.MONITOR and not is_email:
        if "NOTIFICATION_DM_MONITOR_ENABLED" in user_properties:
            is_disabled = True
    elif category == MessageCategories.MONITOR and is_email:
        if "NOTIFICATION_EMAIL_MONITOR_ENABLED" in user_properties:
            is_disabled = True

    return is_disabled


def create_global_message(message, subject) -> None:
    # Enter the message into the database.
    _create_message(-1, None, message, subject, is_global=True)

    if not is_email_enabled():
        logger.warning("Email is disabled. Not sending global email")
        return

    # Send Email to all users.
    try:
        msg = render_template(
            "email/email_notification.html",
            message_content=message,
            pretty_name=current_app.config["APP_PRETTY_NAME"],
            app_site=current_app.config["APP_WEBSITE"],
        )

        send_global_email.apply_async([subject, msg])
    except OperationalError as error:
        logger.error("ERROR: Unable to communicate with Celery Backend.")
        logger.error(error)


def create_direct_message(
    sender_id: int,
    recipient_id: int,
    message: str,
    subject: str,
    category: MessageCategories = MessageCategories.NOT_SET,
) -> None:
    user_obj = UserSql.query.filter_by(user_id=recipient_id).first()

    rendered_message = render_template(
        "email/email_notification.html",
        message_content=message,
        pretty_name=current_app.config["APP_PRETTY_NAME"],
        app_site=current_app.config["APP_WEBSITE"],
    )

    if category == MessageCategories.NOT_SET:
        logger.error("Message category not set.")

    elif category == MessageCategories.ADMIN:
        # The admin category cannot be disabled.
        _create_message(sender_id, recipient_id, message, subject, is_global=False)

        if not is_email_enabled():
            logger.warning("Email is disabled. Not sending ADMIN email")
            return

        try:
            send_email.apply_async(
                [
                    current_app.config["DEFAULT_ADMIN_EMAIL"],
                    subject,
                    [user_obj.email],
                    rendered_message,
                ]
            )
        except OperationalError as error:
            logger.error("ERROR: Unable to communicate with Celery Backend.")
            logger.error(error)

    elif category == MessageCategories.SOCIAL or category == MessageCategories.MONITOR:
        if not _is_user_category_disabled(recipient_id, category):
            _create_message(sender_id, recipient_id, message, subject, is_global=False)

        if not is_email_enabled():
            logger.warning("Email is disabled. Not sending SOCIAL/MONITOR email")
            return

        if not _is_user_category_disabled(recipient_id, category, is_email=True):
            # Send Email to all users.
            try:
                send_email.apply_async(
                    [
                        current_app.config["DEFAULT_MAIL_SENDER"],
                        subject,
                        [user_obj.email],
                        rendered_message,
                    ]
                )
            except OperationalError as error:
                logger.error("ERROR: Unable to communicate with Celery Backend.")
                logger.error(error)


def message_user_list(
    sender_id: int, user_id_list: list, message: str, subject: str, category: MessageCategories
) -> None:
    final_user_list = []
    # First send out, one by one, direct messages to each user, if they're enabled.
    for recipient_id in user_id_list:
        if not _is_user_category_disabled(recipient_id, category):
            _create_message(sender_id, recipient_id, message, subject, is_global=False)

        # Determine, who on the list has email enabled in this loop.
        if not _is_user_category_disabled(recipient_id, category, is_email=True):
            user = UserSql.query.filter_by(user_id=recipient_id).first()
            final_user_list.append(user.email)

    # If the final user list is empty, we don't need to send out any emails.
    if len(final_user_list) == 0:
        logger.debug("No users to send email to.")
        return

    # From the final list, send out the email all at once.
    try:
        send_email.apply_async(
            [
                # This is the sender email. Okay to use app config because it never changes.
                current_app.config["DEFAULT_MAIL_SENDER"],
                subject,
                final_user_list,
                message,
            ],
            # Wait a second before running.
            countdown=1,
        )
    except OperationalError as error:
        logger.error("ERROR: Unable to communicate with Celery Backend.")
        logger.error(error)


def get_direct_messages():
    """Return unexpired & global notification types only."""
    last_read_time = current_user.last_message_read_time or datetime(1900, 1, 1)
    return (
        Messages.query.filter_by(recipient=current_user)
        .filter(Messages.timestamp > last_read_time)
        .all()
    )


def get_global_messages():
    """Return unexpired & global notification types only."""
    last_read_time = current_user.last_message_read_time or datetime(1900, 1, 1)
    return (
        Messages.query.filter_by(is_global=True).filter(Messages.timestamp > last_read_time).all()
    )

application/api/protected/__init__.py
"""Define protected app views."""

application/uix/protected/views.py
import stripe

from datetime import datetime
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    current_app,
    redirect,
    url_for,
)
from flask_login import login_required, current_user

from application.api import users, messages
from application.common import logger
from application.common.tools import (
    verified_required,
    admin_required,
    _get_setting,
)
from application.extensions import DATABASE
from application.models.user import UserSql
from application.models.setting import SettingsSql
from application.uix.protected.forms import (
    AccountProfileForm,
    AccountUpdatePasswordForm,
    GlobalMessageForm,
    DirectMessageForm,
)

protected = Blueprint("protected", __name__, url_prefix="/app")


@protected.route("/main")
@login_required
def main():
    return render_template("uix/app.html", pretty_name=current_app.config["APP_PRETTY_NAME"])


@protected.route("/dashboard")
@login_required
def dashboard():
    return render_template("uix/dashboard.html", pretty_name=current_app.config["APP_PRETTY_NAME"])


@protected.route("/system/agents")
@login_required
@verified_required
def system_agents():
    is_empty = request.args.get("empty", True, type=str)
    if is_empty == "False" or is_empty == "false":
        is_empty = False
    fake_agent_list = [
        {"hostname": "someplace.somewhere.com", "port": "3000", "owner": "Me", "status": "Alive"}
    ]
    return render_template(
        "uix/system_agents.html",
        pretty_name=current_app.config["APP_PRETTY_NAME"],
        is_empty=is_empty,
        agents=fake_agent_list,
    )


@protected.route("/system/crews")
@login_required
@verified_required
def system_crews():
    is_empty = request.args.get("empty", True, type=str)
    if is_empty == "False" or is_empty == "false":
        is_empty = False

    fake_crew_list = [{"name": "Hammer", "owner": "Me", "members": 5, "agents": 2}]
    return render_template(
        "uix/system_crews.html",
        pretty_name=current_app.config["APP_PRETTY_NAME"],
        is_empty=is_empty,
        crews=fake_crew_list,
    )


@protected.route("/system/friends")
@login_required
@verified_required
def system_friends():
    is_empty = request.args.get("empty", True, type=str)
    if is_empty == "False" or is_empty == "false":
        is_empty = False
    fake_friend_list = [{"name": "John Doe", "Crews": 1, "Agents": 3}]
    return render_template(
        "uix/system_friends.html",
        pretty_name=current_app.config["APP_PRETTY_NAME"],
        is_empty=is_empty,
        friends=fake_friend_list,
    )


# @protected.route("/example/verified/page")
# @login_required
# @verified_required
# def example_verified_page():
#     return render_template(
#         "uix/example_verified_page.html",
#         pretty_name=current_app.config["APP_PRETTY_NAME"],
#     )


# @protected.route("/example/paid/page")
# @login_required
# @verified_required
# @subscription_required
# def example_paid_page():
#     return render_template(
#         "uix/example_paid_page.html", pretty_name=current_app.config["APP_PRETTY_NAME"]
#     )


@protected.route("/success")
def success():
    return redirect(url_for("protected.account", tab="billing"))


@protected.route("/account/update/password", methods=["GET", "POST"])
@login_required
def update_account_password():
    if request.method == "POST":
        if not users.update_profile_password(request):
            flash("Password did not match!", "danger")

    return redirect(url_for("protected.account"))


@protected.route("/account", methods=["GET", "POST"])
@login_required
def account():
    profile_form = AccountProfileForm()
    update_password_form = AccountUpdatePasswordForm()

    verified = "True" if current_user.verified else "False"

    active_tab = request.args.get("tab", "account", type=str)

    if request.method == "POST":
        if not users.update_profile(request):
            # Redirect back to GET of this same endpoint. This
            # ensures user loader updates current_user object.
            flash("Unable to update profile!", "danger")

            return redirect(url_for("protected.account"))

    else:
        return render_template(
            "uix/account.html",
            profile_form=profile_form,
            update_password_form=update_password_form,
            verified=verified,
            active_tab=active_tab,
            pretty_name=current_app.config["APP_PRETTY_NAME"],
            payments_enabled=current_app.config["APP_ENABLE_PAYMENTS"],
            email_enabled=current_app.config["APP_ENABLE_EMAIL"],
        )

    return redirect(url_for("protected.account"))


@protected.route("/create-checkout-session", methods=["POST", "GET"])
@login_required
def create_checkout_session():
    price_type = request.args.get("price_type", "NONE", str)

    if price_type == "MONTHLY":
        settings_obj = SettingsSql.query.filter_by(name="STRIPE_MONTHLY_PRICE_ID").first()
        price_id = settings_obj.value
    elif price_type == "ANNUAL":
        settings_obj = SettingsSql.query.filter_by(name="STRIPE_ANNUAL_PRICE_ID").first()
        price_id = settings_obj.value
    else:
        logger.critical("Error: Incorrect price type supplied for check out session.")
        return "", 400

    setting_objs = SettingsSql.query.filter_by(category="payments").all()
    stripe_secret_key = _get_setting("STRIPE_SECRET_KEY", setting_objs)

    stripe.api_key = stripe_secret_key

    http_mode = "http" if current_app.config["ENV"] == "development" else "https"

    success_url = f"{http_mode}://{request.host}/app/success" + "?session_id={CHECKOUT_SESSION_ID}"
    cancel_url = f"{http_mode}://{request.host}/app/account?tab=billing"

    logger.info(f"Success URL: {success_url}")
    logger.info(f"Cancel URL: {cancel_url}")

    line_items = [
        {
            "price": price_id,
            "quantity": 1,
        },
    ]

    try:
        if current_user.customer_id:
            # Existing / Returning Customer
            checkout_session = stripe.checkout.Session.create(
                line_items=line_items,
                customer=current_user.customer_id,
                mode="subscription",
                success_url=success_url,
                cancel_url=cancel_url,
                allow_promotion_codes=True,
                customer_update={"address": "auto"},
                payment_method_collection="if_required",
            )
        else:
            # New customer
            checkout_session = stripe.checkout.Session.create(
                line_items=line_items,
                customer_email=current_user.email,
                mode="subscription",
                success_url=success_url,
                cancel_url=cancel_url,
                allow_promotion_codes=True,
                payment_method_collection="if_required",
            )
    except Exception as error:
        logger.critical(error)
        return str(error), 500

    return redirect(checkout_session.url, code=303)


@protected.route("/customer_portal", methods=["GET", "POST"])
@login_required
def customer_portal():
    # Set secret key

    setting_objs = SettingsSql.query.filter_by(category="payments").all()
    stripe_secret_key = _get_setting("STRIPE_SECRET_KEY", setting_objs)
    # monthly_price_id =  _get_setting("STRIPE_MONTHLY_PRICE_ID", setting_objs)
    # annual_price_id =  _get_setting("STRIPE_ANNUAL_PRICE_ID", setting_objs)

    stripe.api_key = stripe_secret_key

    privacy_policy_url = url_for("public.privacy_policy", _external=True).replace("http", "https")
    terms_url = url_for("public.terms_and_conditions", _external=True).replace("http", "https")

    # Build customer portal.
    # Reference API:
    # https://stripe.com/docs/api/customer_portal/configurations/create?lang=python#create_portal_configuration-features
    portal_config = stripe.billing_portal.Configuration.create(
        features={
            "customer_update": {
                "enabled": True,
                "allowed_updates": ["address", "phone"],
            },
            "subscription_cancel": {"enabled": True, "mode": "at_period_end"},
            # "subscription_update":{
            #     "enabled": True,
            #     "default_allowed_updates": ["price"]
            # },
            "invoice_history": {"enabled": True},
            "payment_method_update": {"enabled": True},
        },
        business_profile={
            "headline": "Thank you for being a customer!",
            "privacy_policy_url": privacy_policy_url,
            "terms_of_service_url": terms_url,
        },
    )

    response = stripe.billing_portal.Session.create(
        customer=current_user.customer_id,
        return_url=f"http://{request.host}/app/account?tab=billing",
        configuration=portal_config,
    )

    # Get the portal url
    portal_url = response["url"]

    # Redirect to the portal
    return redirect(portal_url)


@protected.route("/admin/submit/global", methods=["POST"])
@admin_required
def admin_submit_global_message():
    global_message = GlobalMessageForm()

    if request.method == "POST" and global_message.validate_on_submit():
        messages.create_global_message(global_message.message.data, global_message.subject.data)
        global_message.message.data = ""
        global_message.subject.data = ""

    return redirect(url_for("protected.admin"))


@protected.route("/admin/submit/direct", methods=["POST"])
@admin_required
def admin_submit_direct_message():
    message = DirectMessageForm()

    if request.method == "POST" and message.validate_on_submit():
        logger.info("Evaluating DIRECT Message POST....")
        messages.create_direct_message(
            1, message.recipient_id.data, message.message.data, message.subject.data
        )
        message.recipient_id.data = ""
        message.subject.data = ""
        message.message.data = ""

    return redirect(url_for("protected.admin"))

application/templates/protected/agent_empty_state.html
<section class="height-70">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-6 col-lg-5">
                <div class="card card-lg text-center">
                    <div class="card-body">
                        <i class="icon-add-to-list display-4 opacity-20"></i>
                        <h1 class="h5">There are no Agents of the System yet...</h1>
                        <p>
                            Install <a href="https://github.com/agentsofthesystem/agent-smith/releases" target="_blank">Agent Smith</a> first, and then add to the System.
                        </p>
                        <button class="btn btn-success btn-lg" onclick="showNewAgentModal()">Add An Agent</button>
                    </div>
                </div>
            </div>
            <!--end of col-->
        </div>
        <!--end of row-->
    </div>
    <!--end of container-->
</section>

application/templates/protected/groups_empty_state.html
<section class="height-70">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-6 col-lg-5">
                <div class="card card-lg text-center">
                    <div class="card-body">
                        <i class="icon-add-to-list display-4 opacity-20"></i>
                        <h1 class="h5">No groups have been created.</h1>

                        <button class="btn btn-lg btn-success" onclick="showNewGroupModal()">Create a Group</button>
                    </div>
                </div>
            </div>
            <!--end of col-->
        </div>
        <!--end of row-->
    </div>
    <!--end of container-->
</section>

application/templates/protected/pricing_internal.html
{% extends "layout/base.html" %}

{% block area %}
<div class="main-container">
    {% include 'layout/pricing_info.html' %}
</div>
{% endblock %}

application/templates/protected/system_agent_logs.html
{% extends "layout/base.html" %}

{% block head %}

{{super()}}

{% endblock %}

{% block area %}
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="agent-id" content="{{ agent_info['agent']['agent_id'] }}">

<!-- Modal -->
<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="message-title" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Agent is Unreachable</h5>
      </div>

      <div class="modal-body">
        <p>There has been an error retrieving information from the Agent. It's not reachable
          at the Host/Port provided.</p>

        <p>Please go back to the <a href="{{url_for('protected.system_agents')}}">Agents</a> page.</p>

      </div>

      <div class="modal-footer">
        <a type="button" class="btn btn-secondary" href="{{url_for('protected.system_agents')}}">Go to Agents Page</a>
      </div>
    </div>
  </div>
</div>

<div class="container">

  <!--Agent Info Header-->
  <section class="bg-white space-sm">
    <div class="container">
      <div class="row justify-content-between">
        <div class="col">
          <div class="media align-items-center">
            {% if current_user.user_id == agent_info['agent']['owner_id'] %}
            <img alt="I own this Agent" src="{{ url_for('static', filename='assets/img/agent-black.svg') }}"
              class="avatar avatar-lg avatar-square rounded" />
            {% else %}
            <img alt="Shared Agent" src="{{ url_for('static', filename='assets/img/agent-green.png') }}"
              class="avatar avatar-lg avatar-square rounded" />
            {% endif %}
            <div class="media-body">
              <h1 class="mb-0"><strong>Agent Name:</strong> {{agent_info['agent']['name']}} </h1>
              <h2 class="lead mb-2">Agent URL/Port: {{agent_info['agent']['hostname']}}:{{agent_info['agent']['port']}}
              </h2>
              <div class="d-flex align-items-center">
                <span class="badge badge-secondary mr-3">Owned By: {{agent_info['agent']['owner']['username']}}</span>
                <ul class="list-inline text-small d-inline-block">
                  <!-- Groups -->
                  <li class="list-inline-item"><i class="icon-globe"></i> Groups: {{agent_info['num_groups']}}</li>
                  <!-- Groups -->
                  <li class="list-inline-item"><i class="icon-game-controller"></i> Friends:
                    {{agent_info['num_friends']}}</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <!--end of col-->
        <div class="col-auto">
          <div class="btn-group mb-2">
            <button type="button" class="btn btn-success dropdown-toggle dropdown-toggle-split dropdown-toggle-no-arrow"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="icon-dots-three-horizontal"></i>
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            {% set is_enabled = '' if current_user.user_id == agent_info['agent']['owner_id'] else 'disabled' %}
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-sm">
              <a class="dropdown-item {{is_enabled}}" onclick="clearAgentLogs()">Clear Logs</a>
            </div>
          </div>
        </div>
        <!--end of col-->
      </div>
      <!--end of row-->
    </div>
    <!--end of container-->
  </section>
  <!--end of section-->

  <section class="bg-white flush-with-above">

    <div class="container">
      <div class="card" id="agent-activity-section">
        <div class="card-header">
          <span class="h4">Activity Logs</span>
        </div>
        <div class="card-body">
          {% if current_user.subscribed %}
            <span class="h6 text-red">Unlimited Log Access.</span>
          {% else %}
            <span class="h6 text-blue">Restricted to last 3 logs.</span>
          {% endif %}
          <table class="table table-bordered table-hover align-items-center display" id="activity-log-table">
            <thead>
                <tr>
                    <th scope="col">User</th>
                    <th scope="col">Timestamp</th>
                    <th scope="col">Message</th>
                </tr>
            </thead>
            <tbody class="bg-white">
                {% for log in agent_logs %}
                  <tr>
                      {% if log['is_automated'] %}
                        <td><span class="badge badge-warning">Automated</span></td>
                      {% else %}
                        <td><span class="badge badge-success">{{log['username']}}</span></td>
                      {% endif %}
                      <td>{{log['timestamp']}}</td>
                      <td>{{log['message']}}</td>
                  </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </section>
  <!--end of section-->

</div>
{% endblock %}

{% block scripts %}

{{super()}}

<script>


  var agent_logs_base_url = "/app/system/agent/logs"

  function reloadAgentLogs(agent_id) {
    document.location.href = agent_logs_base_url + '/' + agent_id;
  }

  document.addEventListener('keydown', function (event) {
    // Check if F5 key was pressed
    var agent_id = $('meta[name=agent-id]').attr('content');

    if (event.keyCode === 116) {
        // Prevent the default behavior of the F5 key (page reload)
        event.preventDefault();

        reloadAgentLogs(agent_id);
    }
  });

  $(document).ready(function () {
    var csrftoken = $('meta[name=csrf-token]').attr('content');

    // Takes out the agent id. So it doesn't show up in URL and give people ideas.
    window.history.replaceState(null, "", agent_logs_base_url);

    $('#activity-log-table').DataTable({
      responsive: true,
    });

    $.ajaxSetup({
      beforeSend: function (xhr, settings) {
          if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken)
          }
      }
    })
  });

  function clearAgentLogs(){
    var agent_id = $('meta[name=agent-id]').attr('content');

    $.ajax({
      url: '/app/backend/agent/logs/clear/' + agent_id ,
      type: 'DELETE',
      success: function (data) {
        reloadAgentLogs(agent_id);
      }
    });
  }



</script>


{% endblock %}

application/templates/protected/system_friend_code_form.html
<div class="container mt-2">

    <div class="row justify-content-center">

        <form class="col-24 col-lg-12" action="{{url_for('protected.system_friends')}}" method="post">
            {{ friend_request_form.csrf_token }}
            <div class="card card-sm text-center">
                <div class="card-body row no-gutters align-items-center">
                    <div class="col-auto d-none d-sm-block">
                        <h6 class="title-decorative">New Friend Request:</h6>
                    </div>
                    <!--end of col-->
                    <div class="col">
                        {{ friend_request_form.friend_code(class="form-control form-control-lg
                        form-control-borderless", type="text", id="friend-code", placeholder="Paste Friend Code!") }}
                    </div>
                    <!--end of col-->
                    <div class="col-auto">
                        <button class="btn btn-lg btn-success friend-code-copy" type="submit">Send</button>
                    </div>
                    <!--end of col-->
                </div>
            </div>

        </form>
        <!--end of form-->
    </div>
    <!--end of row-->
</div>
<!--end of container-->

application/templates/protected/system_friends.html
{% extends "layout/base.html" %}

{% block area %}

<meta name="csrf-token" content="{{ csrf_token() }}">

<div class="col text-center">

    {% if request_list_empty %}
        <section class="flush-with-above space-0">
            {% include "protected/system_friend_code_form.html" %}
        </section>
        {% if not friend_list_empty %}
        <section class="flush-with-above space-0">
            <div class="container">
                {% include "protected/system_friend_list.html" %}
            </div>
        </section>
        {% endif %}
    {% else %}

    <section class="flush-with-above space-0">

        {% include "protected/system_friend_code_form.html" %}

        <div class="container">
            <div class="row justify-content-center">
                <div class="col text-center">
                    <ul class="nav nav-tabs" id="myMessagesTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="friend-request-tab" data-toggle="tab"
                                href="#friend-requests" role="tab" aria-selected="true">Friend Requests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="friend-list-tab" data-toggle="tab" href="#friend-list"
                                role="tab" aria-selected="true">Friend List</a>
                        </li>
                    </ul>
                </div>
                <!--end of col-->
            </div>
            <!--end of row-->
        </div>
        <!--end of container-->
    </section>

    <section class="flush-with-above d-block">

        <div class="tab-content">
            <div class="tab-pane fade show active justify-content-center" id="friend-requests" role="tabpanel">
                <div class="container">
                    {% include "protected/system_friend_request_list.html" %}
                </div>
            </div>

            <!--end of tab pane-->
            <div class="tab-pane fade" id="friend-list" role="tabpanel">
                <div class="container">
                    {% include "protected/system_friend_list.html" %}
                </div>
                <!--end of container-->

            </div>
            <!--end of tab pane-->
        </div>
        <!--end of tabs content-->
    </section>
    {% endif %}
</div>

<!--end of row-->
<div class="container">
    <div class="col">
    <div class="d-flex justify-content-end align-items-center mb-4">
        <a href="https://docs.agentsofthesystem.com/build/html/architect/agents.html#groups-vs-friends" target="_blank" class="btn btn-lg btn-success"><span>&nbsp;<i class="icon-info text-grey"></i></span></a>
    </div>
</div>
<!--end of col-->

{% endblock %}

{% block scripts %}
{{super()}}
<script>
    function showAddFriendModal() {
        $('#addFriendModal').modal('show')
    }
    function changePage() {
        document.location.href = "{{url_for('protected.system_friends', empty=False)}}";
    }
</script>
{% endblock %}