application/uix/protected/views.py
import stripe

from datetime import datetime
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    current_app,
    redirect,
    url_for,
)
from flask_login import login_required, current_user

from application.api import users, messages
from application.common import logger
from application.common.tools import (
    verified_required,
    admin_required,
    _get_setting,
)
from application.extensions import DATABASE
from application.models.user import UserSql
from application.models.setting import SettingsSql
from application.uix.protected.forms import (
    AccountProfileForm,
    AccountUpdatePasswordForm,
    GlobalMessageForm,
    DirectMessageForm,
)

protected = Blueprint("protected", __name__, url_prefix="/app")


@protected.route("/main")
@login_required
def main():
    return render_template("uix/app.html", pretty_name=current_app.config["APP_PRETTY_NAME"])


@protected.route("/dashboard")
@login_required
def dashboard():
    return render_template("uix/dashboard.html", pretty_name=current_app.config["APP_PRETTY_NAME"])


@protected.route("/system/agents")
@login_required
@verified_required
def system_agents():
    is_empty = request.args.get("empty", True, type=str)
    if is_empty == "False" or is_empty == "false":
        is_empty = False
    fake_agent_list = [
        {"hostname": "someplace.somewhere.com", "port": "3000", "owner": "Me", "status": "Alive"}
    ]
    return render_template(
        "uix/system_agents.html",
        pretty_name=current_app.config["APP_PRETTY_NAME"],
        is_empty=is_empty,
        agents=fake_agent_list,
    )


@protected.route("/system/crews")
@login_required
@verified_required
def system_crews():
    is_empty = request.args.get("empty", True, type=str)
    if is_empty == "False" or is_empty == "false":
        is_empty = False

    fake_crew_list = [{"name": "Hammer", "owner": "Me", "members": 5, "agents": 2}]
    return render_template(
        "uix/system_crews.html",
        pretty_name=current_app.config["APP_PRETTY_NAME"],
        is_empty=is_empty,
        crews=fake_crew_list,
    )


@protected.route("/system/friends")
@login_required
@verified_required
def system_friends():
    is_empty = request.args.get("empty", True, type=str)
    if is_empty == "False" or is_empty == "false":
        is_empty = False
    fake_friend_list = [{"name": "John Doe", "Crews": 1, "Agents": 3}]
    return render_template(
        "uix/system_friends.html",
        pretty_name=current_app.config["APP_PRETTY_NAME"],
        is_empty=is_empty,
        friends=fake_friend_list,
    )


# @protected.route("/example/verified/page")
# @login_required
# @verified_required
# def example_verified_page():
#     return render_template(
#         "uix/example_verified_page.html",
#         pretty_name=current_app.config["APP_PRETTY_NAME"],
#     )


# @protected.route("/example/paid/page")
# @login_required
# @verified_required
# @subscription_required
# def example_paid_page():
#     return render_template(
#         "uix/example_paid_page.html", pretty_name=current_app.config["APP_PRETTY_NAME"]
#     )


@protected.route("/success")
def success():
    return redirect(url_for("protected.account", tab="billing"))


@protected.route("/account/update/password", methods=["GET", "POST"])
@login_required
def update_account_password():
    if request.method == "POST":
        if not users.update_profile_password(request):
            flash("Password did not match!", "danger")

    return redirect(url_for("protected.account"))


@protected.route("/account", methods=["GET", "POST"])
@login_required
def account():
    profile_form = AccountProfileForm()
    update_password_form = AccountUpdatePasswordForm()

    verified = "True" if current_user.verified else "False"

    active_tab = request.args.get("tab", "account", type=str)

    if request.method == "POST":
        if not users.update_profile(request):
            # Redirect back to GET of this same endpoint. This
            # ensures user loader updates current_user object.
            flash("Unable to update profile!", "danger")

            return redirect(url_for("protected.account"))

    else:
        return render_template(
            "uix/account.html",
            profile_form=profile_form,
            update_password_form=update_password_form,
            verified=verified,
            active_tab=active_tab,
            pretty_name=current_app.config["APP_PRETTY_NAME"],
            payments_enabled=current_app.config["APP_ENABLE_PAYMENTS"],
            email_enabled=current_app.config["APP_ENABLE_EMAIL"],
        )

    return redirect(url_for("protected.account"))


@protected.route("/create-checkout-session", methods=["POST", "GET"])
@login_required
def create_checkout_session():
    price_type = request.args.get("price_type", "NONE", str)

    if price_type == "MONTHLY":
        settings_obj = SettingsSql.query.filter_by(name="STRIPE_MONTHLY_PRICE_ID").first()
        price_id = settings_obj.value
    elif price_type == "ANNUAL":
        settings_obj = SettingsSql.query.filter_by(name="STRIPE_ANNUAL_PRICE_ID").first()
        price_id = settings_obj.value
    else:
        logger.critical("Error: Incorrect price type supplied for check out session.")
        return "", 400

    setting_objs = SettingsSql.query.filter_by(category="payments").all()
    stripe_secret_key = _get_setting("STRIPE_SECRET_KEY", setting_objs)

    stripe.api_key = stripe_secret_key

    http_mode = "http" if current_app.config["ENV"] == "development" else "https"

    success_url = f"{http_mode}://{request.host}/app/success" + "?session_id={CHECKOUT_SESSION_ID}"
    cancel_url = f"{http_mode}://{request.host}/app/account?tab=billing"

    logger.info(f"Success URL: {success_url}")
    logger.info(f"Cancel URL: {cancel_url}")

    line_items = [
        {
            "price": price_id,
            "quantity": 1,
        },
    ]

    try:
        if current_user.customer_id:
            # Existing / Returning Customer
            checkout_session = stripe.checkout.Session.create(
                line_items=line_items,
                customer=current_user.customer_id,
                mode="subscription",
                success_url=success_url,
                cancel_url=cancel_url,
                allow_promotion_codes=True,
                customer_update={"address": "auto"},
                payment_method_collection="if_required",
            )
        else:
            # New customer
            checkout_session = stripe.checkout.Session.create(
                line_items=line_items,
                customer_email=current_user.email,
                mode="subscription",
                success_url=success_url,
                cancel_url=cancel_url,
                allow_promotion_codes=True,
                payment_method_collection="if_required",
            )
    except Exception as error:
        logger.critical(error)
        return str(error), 500

    return redirect(checkout_session.url, code=303)


@protected.route("/customer_portal", methods=["GET", "POST"])
@login_required
def customer_portal():
    # Set secret key

    setting_objs = SettingsSql.query.filter_by(category="payments").all()
    stripe_secret_key = _get_setting("STRIPE_SECRET_KEY", setting_objs)
    # monthly_price_id =  _get_setting("STRIPE_MONTHLY_PRICE_ID", setting_objs)
    # annual_price_id =  _get_setting("STRIPE_ANNUAL_PRICE_ID", setting_objs)

    stripe.api_key = stripe_secret_key

    privacy_policy_url = url_for("public.privacy_policy", _external=True).replace("http", "https")
    terms_url = url_for("public.terms_and_conditions", _external=True).replace("http", "https")

    # Build customer portal.
    # Reference API:
    # https://stripe.com/docs/api/customer_portal/configurations/create?lang=python#create_portal_configuration-features
    portal_config = stripe.billing_portal.Configuration.create(
        features={
            "customer_update": {
                "enabled": True,
                "allowed_updates": ["address", "phone"],
            },
            "subscription_cancel": {"enabled": True, "mode": "at_period_end"},
            # "subscription_update":{
            #     "enabled": True,
            #     "default_allowed_updates": ["price"]
            # },
            "invoice_history": {"enabled": True},
            "payment_method_update": {"enabled": True},
        },
        business_profile={
            "headline": "Thank you for being a customer!",
            "privacy_policy_url": privacy_policy_url,
            "terms_of_service_url": terms_url,
        },
    )

    response = stripe.billing_portal.Session.create(
        customer=current_user.customer_id,
        return_url=f"http://{request.host}/app/account?tab=billing",
        configuration=portal_config,
    )

    # Get the portal url
    portal_url = response["url"]

    # Redirect to the portal
    return redirect(portal_url)


@protected.route("/admin/submit/global", methods=["POST"])
@admin_required
def admin_submit_global_message():
    global_message = GlobalMessageForm()

    if request.method == "POST" and global_message.validate_on_submit():
        messages.create_global_message(global_message.message.data, global_message.subject.data)
        global_message.message.data = ""
        global_message.subject.data = ""

    return redirect(url_for("protected.admin"))


@protected.route("/admin/submit/direct", methods=["POST"])
@admin_required
def admin_submit_direct_message():
    message = DirectMessageForm()

    if request.method == "POST" and message.validate_on_submit():
        logger.info("Evaluating DIRECT Message POST....")
        messages.create_direct_message(
            1, message.recipient_id.data, message.message.data, message.subject.data
        )
        message.recipient_id.data = ""
        message.subject.data = ""
        message.message.data = ""

    return redirect(url_for("protected.admin"))

application/templates/uix/app.html
{% extends "layout/base.html" %}

{% block area %}
<div class="col text-center">
    <p> After Login Landing Page </p>
</div>
{% endblock %}

application/templates/uix/billing.html
<div class="container">
    <div class="row justify-content-center">
           
            <!--end of col-->
            <div class="col-md-6 col-lg-5">
              <div class="card pricing card-lg">
                <div class="card-body">
                  <h5>Pro Monthly</h5>
                  <span class="display-3">$20</span>
                  <span class="text-small">per / month</span>
                  <span class="h6">Includes:</span>
                  <ul class="list-unstyled">
                    <li>
                      1 Active project
                    </li>
                    <li>
                      2 Repositories
                    </li>
                    <li>
                      2 Collaborators
                    </li>
                  </ul>
                  <button id="pro-monthly-btn" class="btn btn-lg btn-outline-primary">Purchase</button>
                </div>
              </div>
              <!--end card-->
            </div>
            <!--end of col-->
            <div class="col-md-6 col-lg-5">
              <div class="card pricing card-lg">
                <div class="card-body">
                  <h5>Pro Annual</h5>
                  <span class="display-3">$200</span>
                  <span class="text-small">per / year</span>
                  <span class="h6">Includes:</span>
                  <ul class="list-unstyled">
                    <li>
                        1 Active project
                      </li>
                      <li>
                        2 Repositories
                      </li>
                      <li>
                        2 Collaborators
                      </li>
                  </ul>
                  <button id="pro-annual-btn" class="btn btn-lg btn-outline-primary">Purchase</button>
                </div>
              </div>
              <!--end card-->
            </div>
            <!--end of col-->
          </div>
</div>

<script>

    document
      .getElementById("pro-monthly-btn")
      .addEventListener("click", function (evt) {
        //redirectToCheckout(SUBSCRIPTION_PRO_MONTHLY_PRICE_ID);
        window.location.href = '/app/create-checkout-session?price_type=MONTHLY'
      });

    document
      .getElementById("pro-annual-btn")
      .addEventListener("click", function (evt) {
        //redirectToCheckout(SUBSCRIPTION_PRO_ANNUAL_PRICE_ID);
        window.location.href = '/app/create-checkout-session?price_type=ANNUAL'
      });
      
  </script>

application/templates/uix/crews_empty_state.html
<section class="height-70">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-6 col-lg-5">
                <div class="card card-lg text-center">
                    <div class="card-body">
                        <i class="icon-add-to-list display-4 opacity-20"></i>
                        <h1 class="h5">This ship has no crew.  Yet...</h1>

                        <a class="btn btn-lg btn-success" onclick="showCreateCrewModal()">Create a Crew</a>
                    </div>
                </div>
            </div>
            <!--end of col-->
        </div>
        <!--end of row-->
    </div>
    <!--end of container-->
</section>

application/templates/uix/empty.html
<!doctype html>
<html lang="en">
    {% include 'layout/head.html' %}
    {% include 'layout/google_analytics.html' %}
    <body>
    {% include 'layout/landing_topbar.html' %}

    <div class="main-container">
        {% include 'layout/footer.html' %}
    </div>

    {% include 'layout/scripts.html' %}
    </body>
</html>

application/templates/uix/example_paid_page.html
{% extends "layout/base.html" %}

{% block area %}
<div class="col text-center">
    <p> This is an example page that only a paying user may see, or if paid pages are not enforced.</p>
</div>
{% endblock %}

application/templates/uix/example_verified_page.html
{% extends "layout/base.html" %}

{% block area %}
<div class="col text-center">
    <p> This is an example of a page that only a user that's verified their email address may see.</p>
</div>
{% endblock %}

application/templates/uix/support.html
<!doctype html>
<html lang="en">

{% include 'layout/head.html' %}
{% include 'layout/google_analytics.html' %}

<body>
    {% include 'layout/landing_topbar.html' %}

    <div class="main-container">
        <section class="space-sm">
          <div class="container align-self-start">
            <div class="row mb-5">
              <div class="col text-center">
                <a href="#">
                  <img alt="Image" src="{{ url_for('static', filename='assets/img/app-logo.svg') }}" />
                </a>
              </div>
              <!--end of col-->
            </div>
            <!--end of row-->
            <div class="row justify-content-center">
              <div class="col-12 col-md-8 col-lg-7">
                <div class="card card-lg text-center">
                  <div class="card-body">
                    <div class="mb-5">
                      <h1 class="h2 mb-2">Get in touch</h1>
                      <span>Need to flesh this out before.</span>
                    </div>
                    <div class="row no-gutters justify-content-center">
                      <p>PUT SOMETHING HERE!</p>
                    </div>
                    <!--end of row-->
                  </div>
                </div>
                <div class="text-center">
                  <span class="text-small">Don't have an account yet? <a href="#">Create one</a>
                  </span>
                </div>
              </div>
              <!--end of col-->
            </div>
            <!--end of row-->
          </div>
          <!--end of container-->
        </section>
        <!--end of section-->
    </div>

    {% include 'layout/footer.html' %}

    {% include 'layout/scripts.html' %}
</body>

</html>

application/templates/uix/system_crew_list.html
</section>
<!--end of section-->
<section class="flush-with-above">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="d-flex justify-content-between align-items-center mb-4">
          <div>
            <span class="text-muted text-small">Results 1 - 8 of 8</span>
          </div>
          <form class="d-flex align-items-center">
            <span class="mr-2 text-muted text-small text-nowrap">Sort by:</span>
            <select class="custom-select">
              <option value="alpha">Alphabetical</option>
              <option value="old-new" selected>Newest</option>
              <option value="new-old">Oldest</option>
            </select>
          </form>
        </div>
      </div>
      <!--end of col-->
    </div>
    <!--end of row-->
    <div class="row">
      <div class="col">
        <table class="table table-borderless table-hover align-items-center">
          <thead>
            <tr>
              <th scope="col">Crew</th>
              <th scope="col">Owner</th>
              <th scope="col">Members</th>
              <th scope="col">Agents</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>

            <tr class="bg-white">
              <th scope="row">
                <a class="media align-items-center">
                  <img alt="Image" src="{{ url_for('static', filename='uix/assets/img/agent.png') }}" class="avatar rounded avatar-sm" />
                  <div class="media-body">
                    <span class="h6 mb-0">The Hammer</span>
                  </div>
                </a>
              </th>
              <td>{{current_user.username}}</td>
              <td>
                5
              </td>
              <td>
                2
              </td>
              <td>
                <div class="dropdown">
                  <button class="btn btn-sm btn-outline-primary dropdown-toggle dropdown-toggle-no-arrow" type="button" id="dropdownMenuButton-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="icon-dots-three-horizontal"></i>
                  </button>
                  <div class="dropdown-menu dropdown-menu-sm">
                    <a class="dropdown-item" href="#">Update Crew</a>
                    <a class="dropdown-item" href="#">Members</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Disband</a>
                  </div>
                </div>
              </td>
            </tr>
            <tr class="table-divider">
              <th></th>
              <td></td>
            </tr>

          </tbody>
        </table>
      </div>
      <!--end of col-->
    </div>
    <!--end of row-->
    <div class="row">
      <div class="col">
        <div class="d-flex justify-content-between align-items-center mb-4">
          <div></div>
          <form class="d-flex align-items-center">
            <a class="btn btn-success btn-lg" onclick="showCreateCrewModal()">New Crew</a>
          </form>
        </div>
      </div>
      <!--end of col-->
    </div>
    <!--end of row-->
  </div>
  <!--end of container-->
</section>

application/templates/uix/system_crews.html
{% extends "uix/layout/base.html" %}

{% block area %}

<!-- Modal -->
<div class="modal fade" id="createCrewModal" tabindex="-1" role="dialog" aria-labelledby="message-title"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create a New Crew</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p> A form will go here </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" onclick="changePage()">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="col text-center">

    {% if is_empty %}
        {% include "uix/crews_empty_state.html" %}
    {% else %}
        {% include "uix/system_crew_list.html" %}
    {% endif %}

</div>
{% endblock %}

{% block scripts %}
{{super()}}
<script>
    function showCreateCrewModal(){
        $('#createCrewModal').modal('show')
    }
    function changePage(){
        document.location.href = "{{url_for('protected.system_crews', empty=False)}}";
    }
</script>
{% endblock %}